In [51]:
# for correct relative imports
import sys; sys.path.append("../var_es_dgm")

In [52]:
import warnings
warnings.filterwarnings("ignore")

import torch
from torch.utils.data import DataLoader, TensorDataset

from diffusers import DDPMScheduler
import pandas as pd
import numpy as np
from tqdm.auto import tqdm
import matplotlib.pyplot as plt
import seaborn as sns
import pprint
import scipy.stats

from sklearn.preprocessing import StandardScaler

from var_es_dgm import TimeGrad
from var_es_dgm.basic_models.deepvar import DeepVaR
from var_es_dgm.basic_models.deepar import DeepAR
from var_es_dgm.basic_models import HistoricalSimulation, VarCov
from var_es_dgm.stat_tests import generate_report
from var_es_dgm.utils import seed_everything, compute_individual_returns, compute_portfolio_returns, estimate_var_es_torch

from arch import arch_model

In [53]:
sns.set_style("darkgrid", {"axes.facecolor": ".9"})
sns.set_context("paper")

In [54]:
DATA_FOLDER = "../../data/"
df = pd.read_csv(DATA_FOLDER + "complete_stocks.csv")
df["Date"] = pd.to_datetime(df["Date"])

In [55]:
len(df["Ticker"].unique())

89

## 5%

In [ ]:
res_timeGrad = list()
res_deepar_normal = list()
res_deepar_student = list()
res_deepvar_paper = list()
res_garch = list() 
res_hist = list()
res_varcov = list()
alpha=0.05
RANDOM_STATE = 12

for i in range(5):
    seed_everything(RANDOM_STATE + i)
    n_stocks = 10
    tickers = np.random.choice(df["Ticker"].unique(), n_stocks, replace=False)
    weights = 1/n_stocks
    print("Portfolio = {0}".format(" + ".join([f"{weights} * {i}"for i in tickers])))
    df_copy = df.loc[df["Ticker"].isin(tickers)].copy(deep=True)

    df_returns = compute_individual_returns(df_copy)
    df_returns = compute_portfolio_returns(df_returns)

    univariate_target = df_returns["Return_Target"]

    univariate_target = univariate_target.values[1:]
    train_size = df_returns[df_returns.Date <= "2022-06-01"].index[-1] + 1
    test_size = len(univariate_target) - train_size
    train = univariate_target[:train_size]

    ss = StandardScaler()
    train_scaled = torch.tensor(ss.fit_transform(train.reshape(-1, 1)), dtype=torch.float32)

    seed_everything(RANDOM_STATE)
    context_size = 90
    num_train_samples = 3000
    train_data = torch.zeros(num_train_samples, context_size, train_scaled.shape[1])
    train_target = torch.zeros(num_train_samples, 1, train_scaled.shape[1])
    train_idx = np.random.choice(np.arange(context_size, train_scaled.shape[0]), num_train_samples, replace=False)
    
    for i in tqdm(range(num_train_samples)):
        idx = train_idx[i]
        train_context = train_scaled[idx-context_size:idx]
        target_obs = train_scaled[idx]
        train_data[i] = train_context
        train_target[i] = target_obs

    train_loader = DataLoader(TensorDataset(train_data, train_target), batch_size=128, shuffle=False)


    temp = torch.tensor(ss.transform(univariate_target.reshape(-1, 1)))
    test_data_context = torch.zeros(test_size, context_size, temp.shape[1])
    test_data_real = torch.zeros(test_size, 1, temp.shape[1])
    for i in range(test_size):
        idx = i + train_size
        test_data_context[i] = temp[idx-context_size:idx]
        test_data_real[i] = temp[idx]

    seed_everything(RANDOM_STATE)
    sheduler = DDPMScheduler(num_train_timesteps=46, beta_end=0.35878774019831244, clip_sample=False)
    model = TimeGrad(1, 1, hidden_size=50, num_layers=2, scheduler=sheduler, num_inference_steps=46)
    
    
    optimizer = torch.optim.Adam(model.parameters(), lr=0.0008985916117829954)
    device = "cuda"
    n_epochs = 31
    model.to(device);

    model.fit(train_loader, optimizer, n_epochs, device)


    seed_everything(RANDOM_STATE)
    VaR_TimeGrad = torch.zeros(test_data_real.shape[0])
    ES_TimeGrad = torch.zeros(test_data_real.shape[0])
    
    for i in tqdm(range(test_data_real.shape[0])):
        test = test_data_context[[i]]
        VaR_TimeGrad[i], ES_TimeGrad[i] = estimate_var_es_torch(model, test, alpha=alpha, n_samples=500, device=device)

    res_timeGrad.append(generate_report(test_data_real.flatten(), VaR_TimeGrad, ES_TimeGrad, alpha=alpha))

    # 2.DeepAR (student)
    seed_everything(RANDOM_STATE)
    model_deepvar_student = DeepAR(
        target_dim=1,  
        input_size=train_data.shape[2],  
        hidden_size=64,  
        num_layers=2,  
        dropout_rate=0.4,
        dist_type='student' 
    )

    optimizer_deepvar = torch.optim.Adam(model_deepvar_student.parameters(), lr=1e-3)
    model_deepvar_student.to(device)

    model_deepvar_student.fit(train_loader, optimizer_deepvar, n_epochs=n_epochs, device=device)

    VaR_deepvar = torch.zeros(test_data_real.shape[0])
    ES_deepvar = torch.zeros(test_data_real.shape[0])
    
    for i in tqdm(range(test_data_real.shape[0]), desc="Testing DeepAR(Student)"):
        test = test_data_context[[i]].to(device)
        VaR_deepvar[i], ES_deepvar[i] = estimate_var_es_torch(model_deepvar_student, test, alpha=alpha, n_samples=500, device=device)

    res_deepar_student.append(generate_report(test_data_real.flatten(), VaR_deepvar, ES_deepvar, alpha=alpha))

    # 3.DeepAR (Normal)
    seed_everything(RANDOM_STATE)
    model_deepvar = DeepAR(
        target_dim=1,  
        input_size=train_data.shape[2],  
        hidden_size=64,  
        num_layers=2,  
        dropout_rate=0.4,
        dist_type='normal' 
    )

    optimizer_deepvar = torch.optim.Adam(model_deepvar.parameters(), lr=1e-3)
    model_deepvar.to(device)

    model_deepvar.fit(train_loader, optimizer_deepvar, n_epochs=n_epochs, device=device)

    VaR_deepvar = torch.zeros(test_data_real.shape[0])
    ES_deepvar = torch.zeros(test_data_real.shape[0])
    
    for i in tqdm(range(test_data_real.shape[0]), desc="Testing DeepAR(Normal)"):
        test = test_data_context[[i]].to(device)
        VaR_deepvar[i], ES_deepvar[i] = estimate_var_es_torch(model_deepvar, test, alpha=alpha, n_samples=500, device=device)

    res_deepar_normal.append(generate_report(test_data_real.flatten(), VaR_deepvar, ES_deepvar, alpha=alpha))

    # 4.DeepVaR (Paper)
    deepvar_framework = DeepVaR(
        model=model_deepvar_student,
        scaler=ss,           
        alpha=alpha,
        n_samples=500,       
        device=device
    )

    VaR_deepvar_paper = torch.zeros(test_data_real.shape[0])
    ES_deepvar_paper = torch.zeros(test_data_real.shape[0])
    
    for i in tqdm(range(test_data_real.shape[0]), desc="Testing DeepVaR (Paper Framework)"):
        test = test_data_context[[i]].to(device)
        v, e = deepvar_framework.predict(test)
        VaR_deepvar_paper[i] = v
        ES_deepvar_paper[i] = e

    res_deepvar_paper.append(generate_report(test_data_real.flatten(), VaR_deepvar_paper, ES_deepvar_paper, alpha=alpha))

    # 5. GARCH(1,1) Model (Возврат к вашему оригиналу)
    VaR_garch = torch.zeros(test_size)
    ES_garch = torch.zeros(test_size)
    
    for j in tqdm(range(test_size), desc="Testing GARCH(1,1)"):
        idx = j + train_size
        start_idx = max(0, idx - 900)
        
        hist_returns = univariate_target[start_idx:idx]
        
        am = arch_model(hist_returns * 100, vol='Garch', p=1, q=1, dist='Normal')
        res = am.fit(disp='off', show_warning=False)
        forecasts = res.forecast(horizon=1, reindex=False)
        
        mu = forecasts.mean.iloc[-1, 0] / 100
        sigma = np.sqrt(forecasts.variance.iloc[-1, 0]) / 100
        
        q = scipy.stats.norm.ppf(alpha)
        VaR_garch[j] = (mu + sigma * q)
        pdf_q = scipy.stats.norm.pdf(q)
        ES_garch[j] = (mu - sigma * (pdf_q / alpha))

    VaR_garch_scaled = torch.tensor(
        ss.transform(VaR_garch.numpy().reshape(-1, 1)).flatten(), 
        dtype=torch.float32
    )
    ES_garch_scaled = torch.tensor(
        ss.transform(ES_garch.numpy().reshape(-1, 1)).flatten(), 
        dtype=torch.float32
    )

    res_garch.append(generate_report(test_data_real.flatten(), VaR_garch_scaled, ES_garch_scaled, alpha=alpha))

    # Результаты для других моделей
    hist_sim = HistoricalSimulation(alpha=alpha)
    VaR_histSim = torch.zeros(test_data_real.shape[0])
    ES_histSim = torch.zeros(test_data_real.shape[0])
    
    for i in tqdm(range(test_data_real.shape[0])):
        test = test_data_context[[i]]
        VaR_histSim[i], ES_histSim[i] = hist_sim.predict(test)
    
    res_hist.append(generate_report(test_data_real.flatten(), VaR_histSim, ES_histSim, alpha=alpha))
    
    var_cov = VarCov(alpha=alpha)
    
    VaR_varCov = torch.zeros(test_data_real.shape[0])
    ES_varCov = torch.zeros(test_data_real.shape[0])
    
    for i in tqdm(range(test_data_real.shape[0])):
        test = test_data_context[[i]]
        VaR_varCov[i], ES_varCov[i] = var_cov.predict(test)
    
    res_varcov.append(generate_report(test_data_real.flatten(), VaR_varCov, ES_varCov, alpha=alpha))

    # Выводим результаты для всех моделей
    print("\n--- Results for Iteration ---")
    print("TimeGrad:      ", res_timeGrad[-1])
    print("DeepAR Normal: ", res_deepar_normal[-1])
    print("DeepAR Student:", res_deepar_student[-1])
    print("DeepVaR Paper: ", res_deepvar_paper[-1])
    print("GARCH(1,1):    ", res_garch[-1])
    print("HistSim:       ", res_hist[-1])
    print("VarCov:        ", res_varcov[-1])

Portfolio = 0.1 * INTC + 0.1 * DHR + 0.1 * COP + 0.1 * MRK + 0.1 * HON + 0.1 * T + 0.1 * MSFT + 0.1 * AXP + 0.1 * PEP + 0.1 * SYK


  0%|          | 0/10 [00:00<?, ?it/s]

  0%|          | 0/3000 [00:00<?, ?it/s]

Epochs:   0%|          | 0/31 [00:00<?, ?it/s]

  0%|          | 0/396 [00:00<?, ?it/s]

Epochs:   0%|          | 0/31 [00:00<?, ?it/s]

Testing DeepAR(Student):   0%|          | 0/396 [00:00<?, ?it/s]

Epochs:   0%|          | 0/31 [00:00<?, ?it/s]

Testing DeepAR(Normal):   0%|          | 0/396 [00:00<?, ?it/s]

Testing DeepVaR (Paper Framework):   0%|          | 0/396 [00:00<?, ?it/s]

Testing GARCH(1,1):   0%|          | 0/396 [00:00<?, ?it/s]

  0%|          | 0/396 [00:00<?, ?it/s]

  0%|          | 0/396 [00:00<?, ?it/s]


--- Results for Iteration ---
TimeGrad:       {'Kupicks POF': 0.0014833268934557478, 'Haas TBF': 0.009519655499408718, 'Christoffersen Test': 0.41313554781681816, 'Kupicks Test': 0.0014833268934557478, 'Acerbi Szekely 1': 2.0068631172180176, 'Acerbi Szekely 2': 0.008868713863193989}
DeepAR Normal:  {'Kupicks POF': 0.6735892621900934, 'Haas TBF': 0.07369408151888043, 'Christoffersen Test': 0.5198444471167137, 'Kupicks Test': 0.6735892621900934, 'Acerbi Szekely 1': 2.112898111343384, 'Acerbi Szekely 2': 0.004802041221410036}
DeepAR Student: {'Kupicks POF': 0.34795084125098275, 'Haas TBF': 0.7043961870122604, 'Christoffersen Test': 0.4663780472039817, 'Kupicks Test': 0.34795084125098275, 'Acerbi Szekely 1': 2.02618408203125, 'Acerbi Szekely 2': 0.006139952223747969}
DeepVaR Paper:  {'Kupicks POF': 0.9632775216835524, 'Haas TBF': 0.28301998296072667, 'Christoffersen Test': 0.5003023342884295, 'Kupicks Test': 0.9632775216835524, 'Acerbi Szekely 1': 2.0510988235473633, 'Acerbi Szekely 2': 0

  0%|          | 0/10 [00:00<?, ?it/s]

  0%|          | 0/3000 [00:00<?, ?it/s]

Epochs:   0%|          | 0/31 [00:00<?, ?it/s]

  0%|          | 0/396 [00:00<?, ?it/s]

Epochs:   0%|          | 0/31 [00:00<?, ?it/s]

Testing DeepAR(Student):   0%|          | 0/396 [00:00<?, ?it/s]

Epochs:   0%|          | 0/31 [00:00<?, ?it/s]

Testing DeepAR(Normal):   0%|          | 0/396 [00:00<?, ?it/s]

Testing DeepVaR (Paper Framework):   0%|          | 0/396 [00:00<?, ?it/s]

Testing GARCH(1,1):   0%|          | 0/396 [00:00<?, ?it/s]

  0%|          | 0/396 [00:00<?, ?it/s]

  0%|          | 0/396 [00:00<?, ?it/s]


--- Results for Iteration ---
TimeGrad:       {'Kupicks POF': 0.07430282357066968, 'Haas TBF': 0.017099870912718983, 'Christoffersen Test': 0.451493118695405, 'Kupicks Test': 0.07430282357066968, 'Acerbi Szekely 1': 1.897748589515686, 'Acerbi Szekely 2': 0.0067092119716107845}
DeepAR Normal:  {'Kupicks POF': 0.8527157106323404, 'Haas TBF': 0.02265682318805066, 'Christoffersen Test': 0.5098255905975888, 'Kupicks Test': 0.8527157106323404, 'Acerbi Szekely 1': 2.011215925216675, 'Acerbi Szekely 2': 0.004824886564165354}
DeepAR Student: {'Kupicks POF': 0.9632775216835524, 'Haas TBF': 0.03195337774011316, 'Christoffersen Test': 0.5098255905975888, 'Kupicks Test': 0.9632775216835524, 'Acerbi Szekely 1': 1.8804346323013306, 'Acerbi Szekely 2': 0.0047485725954174995}
DeepVaR Paper:  {'Kupicks POF': 0.8527157106323404, 'Haas TBF': 0.3383719760985348, 'Christoffersen Test': 0.5003023342884295, 'Kupicks Test': 0.8527157106323404, 'Acerbi Szekely 1': 1.8722777366638184, 'Acerbi Szekely 2': 0.0044

  0%|          | 0/10 [00:00<?, ?it/s]

  0%|          | 0/3000 [00:00<?, ?it/s]

Epochs:   0%|          | 0/31 [00:00<?, ?it/s]

  0%|          | 0/396 [00:00<?, ?it/s]

Epochs:   0%|          | 0/31 [00:00<?, ?it/s]

Testing DeepAR(Student):   0%|          | 0/396 [00:00<?, ?it/s]

Epochs:   0%|          | 0/31 [00:00<?, ?it/s]

Testing DeepAR(Normal):   0%|          | 0/396 [00:00<?, ?it/s]

Testing DeepVaR (Paper Framework):   0%|          | 0/396 [00:00<?, ?it/s]

Testing GARCH(1,1):   0%|          | 0/396 [00:00<?, ?it/s]

  0%|          | 0/396 [00:00<?, ?it/s]

  0%|          | 0/396 [00:00<?, ?it/s]


--- Results for Iteration ---
TimeGrad:       {'Kupicks POF': 0.002837671450535891, 'Haas TBF': 0.016379255682555247, 'Christoffersen Test': 0.41313554781681816, 'Kupicks Test': 0.002837671450535891, 'Acerbi Szekely 1': 1.9271550178527832, 'Acerbi Szekely 2': 0.008273140527307987}
DeepAR Normal:  {'Kupicks POF': 0.15902475231004004, 'Haas TBF': 0.32353418055406563, 'Christoffersen Test': 0.5415791828627718, 'Kupicks Test': 0.15902475231004004, 'Acerbi Szekely 1': 1.9616092443466187, 'Acerbi Szekely 2': 0.0034674913622438908}
DeepAR Student: {'Kupicks POF': 0.24846668808638034, 'Haas TBF': 0.011804282494534612, 'Christoffersen Test': 0.4663780472039817, 'Kupicks Test': 0.24846668808638034, 'Acerbi Szekely 1': 1.8763020038604736, 'Acerbi Szekely 2': 0.005922670941799879}
DeepVaR Paper:  {'Kupicks POF': 0.17166934687383595, 'Haas TBF': 0.023772629293143877, 'Christoffersen Test': 0.45878332977883307, 'Kupicks Test': 0.17166934687383595, 'Acerbi Szekely 1': 1.8189219236373901, 'Acerbi Sze

  0%|          | 0/10 [00:00<?, ?it/s]

  0%|          | 0/3000 [00:00<?, ?it/s]

Epochs:   0%|          | 0/31 [00:00<?, ?it/s]

  0%|          | 0/396 [00:00<?, ?it/s]

Epochs:   0%|          | 0/31 [00:00<?, ?it/s]

Testing DeepAR(Student):   0%|          | 0/396 [00:00<?, ?it/s]

Epochs:   0%|          | 0/31 [00:00<?, ?it/s]

Testing DeepAR(Normal):   0%|          | 0/396 [00:00<?, ?it/s]

Testing DeepVaR (Paper Framework):   0%|          | 0/396 [00:00<?, ?it/s]

Testing GARCH(1,1):   0%|          | 0/396 [00:00<?, ?it/s]

  0%|          | 0/396 [00:00<?, ?it/s]

  0%|          | 0/396 [00:00<?, ?it/s]


--- Results for Iteration ---
TimeGrad:       {'Kupicks POF': 0.016661105618660934, 'Haas TBF': 0.08647791764955066, 'Christoffersen Test': 0.42499904223958085, 'Kupicks Test': 0.016661105618660934, 'Acerbi Szekely 1': 2.0387120246887207, 'Acerbi Szekely 2': 0.007979807443916798}
DeepAR Normal:  {'Kupicks POF': 0.09526169367735128, 'Haas TBF': 0.23376197234148383, 'Christoffersen Test': 0.553424416231153, 'Kupicks Test': 0.09526169367735128, 'Acerbi Szekely 1': 2.0649542808532715, 'Acerbi Szekely 2': 0.0033894453663378954}
DeepAR Student: {'Kupicks POF': 0.11478649504904415, 'Haas TBF': 0.16542951250680468, 'Christoffersen Test': 0.4444870465584825, 'Kupicks Test': 0.11478649504904415, 'Acerbi Szekely 1': 1.9389451742172241, 'Acerbi Szekely 2': 0.006610040552914143}
DeepVaR Paper:  {'Kupicks POF': 0.17166934687383595, 'Haas TBF': 0.24187224857439524, 'Christoffersen Test': 0.451493118695405, 'Kupicks Test': 0.17166934687383595, 'Acerbi Szekely 1': 1.9371142387390137, 'Acerbi Szekely 2

  0%|          | 0/10 [00:00<?, ?it/s]

  0%|          | 0/3000 [00:00<?, ?it/s]

Epochs:   0%|          | 0/31 [00:00<?, ?it/s]

  0%|          | 0/396 [00:00<?, ?it/s]

Epochs:   0%|          | 0/31 [00:00<?, ?it/s]

Testing DeepAR(Student):   0%|          | 0/396 [00:00<?, ?it/s]

Epochs:   0%|          | 0/31 [00:00<?, ?it/s]

Testing DeepAR(Normal):   0%|          | 0/396 [00:00<?, ?it/s]

Testing DeepVaR (Paper Framework):   0%|          | 0/396 [00:00<?, ?it/s]

Testing GARCH(1,1):   0%|          | 0/396 [00:00<?, ?it/s]

  0%|          | 0/396 [00:00<?, ?it/s]

  0%|          | 0/396 [00:00<?, ?it/s]


--- Results for Iteration ---
TimeGrad:       {'Kupicks POF': 0.016661105618660934, 'Haas TBF': 0.004515565475338597, 'Christoffersen Test': 0.4444870465584825, 'Kupicks Test': 0.016661105618660934, 'Acerbi Szekely 1': 1.9401148557662964, 'Acerbi Szekely 2': 0.007593884598463774}
DeepAR Normal:  {'Kupicks POF': 0.15902475231004004, 'Haas TBF': 0.0368803930078606, 'Christoffersen Test': 0.5660290828865208, 'Kupicks Test': 0.15902475231004004, 'Acerbi Szekely 1': 2.0128579139709473, 'Acerbi Szekely 2': 0.0035580822732299566}
DeepAR Student: {'Kupicks POF': 0.3653929983513471, 'Haas TBF': 0.511631620098608, 'Christoffersen Test': 0.5304092795638204, 'Kupicks Test': 0.3653929983513471, 'Acerbi Szekely 1': 1.957792043685913, 'Acerbi Szekely 2': 0.003955135587602854}
DeepVaR Paper:  {'Kupicks POF': 0.2484438497515893, 'Haas TBF': 0.8925929403030177, 'Christoffersen Test': 0.5304092795638204, 'Kupicks Test': 0.2484438497515893, 'Acerbi Szekely 1': 1.9418411254882812, 'Acerbi Szekely 2': 0.00

In [57]:
print(np.array([list(i.values()) for i in res_timeGrad]).mean(axis=0))
print(np.array([list(i.values()) for i in res_deepar_student]).mean(axis=0))
print(np.array([list(i.values()) for i in res_deepar_normal]).mean(axis=0))
print(np.array([list(i.values()) for i in res_deepvar_paper]).mean(axis=0))
print(np.array([list(i.values()) for i in res_garch]).mean(axis=0))
print(np.array([list(i.values()) for i in res_hist]).mean(axis=0))
print(np.array([list(i.values()) for i in res_varcov]).mean(axis=0))

[0.02238921 0.02679845 0.42945006 0.02238921 1.96211872 0.00788495]
[0.40797491 0.285043   0.4834956  0.40797491 1.93593159 0.00547527]
[0.38792323 0.13810549 0.53814054 0.38792323 2.0327071  0.00400839]
[0.48155516 0.35592596 0.48825808 0.48155516 1.92425077 0.00513585]
[0.26790727 0.39737836 0.52973799 0.26790727 2.10132732 0.00428139]
[0.47226877 0.29528794 0.52562327 0.47226877 2.00618947 0.00414766]
[0.20164341 0.2664099  0.55322859 0.20164341 2.02576849 0.00348413]
